/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  safelist: [
    // Brand design system colors
    'bg-brand-dark',
    'bg-brand-darker',
    'border-brand-border',
    'text-brand-primary',
    'text-brand-text-muted',
    'text-brand-text-subtle',
    'text-brand-text-dimmer',
    'bg-brand-border/20',
    // Cluster component colors
    'bg-slate-950',
    'bg-slate-900',
    'bg-gradient-to-b',
    'from-slate-950',
    'to-slate-900',
    'border-zinc-800',
    'border-zinc-700',
    'border-zinc-600',
    'text-zinc-300',
    'text-zinc-400',
    'text-zinc-500',
    'text-zinc-600',
    'text-zinc-700',
    'bg-indigo-600',
    'hover:bg-indigo-700',
    'bg-indigo-900/30',
    'text-indigo-300',
    'text-indigo-400',
    'bg-indigo-500',
    'border-indigo-500',
    'shadow-lg',
    'shadow-indigo-500/10',
    'bg-amber-900/30',
    'text-amber-300',
    'text-amber-400',
    'bg-amber-500',
    'bg-emerald-900/30',
    'text-emerald-300',
    'text-emerald-400',
    'bg-emerald-500',
    'bg-purple-900/30',
    'text-purple-300',
    'text-purple-400',
    'bg-purple-500',
    'bg-blue-900/30',
    'text-blue-300',
    'text-blue-400',
    'bg-blue-500',
    // Layout utilities
    'fixed',
    'top-0',
    'left-0',
    'right-0',
    'z-50',
    'backdrop-blur',
    'bg-gradient-to-t',
    'h-48',
    'aspect-video',
    'line-clamp-2',
    'group',
    'group-hover:scale-105',
    'group-hover:text-indigo-300',
    'group-hover:opacity-100',
    'opacity-0',
    'flex-1',
    'disabled:opacity-50',
    'disabled:cursor-not-allowed',
    // Original category colors for dynamic styling
    'bg-blue-50',
    'bg-blue-600',
    'bg-green-50',
    'bg-green-600',
    'bg-purple-50',
    'bg-purple-600',
    'bg-red-50',
    'bg-red-600',
    'bg-orange-50',
    'bg-orange-600',
    'text-blue-600',
    'text-green-600',
    'text-purple-600',
    'text-red-600',
    'text-orange-600',
    'from-blue-500',
    'from-blue-600',
    'from-green-500',
    'from-green-600',
    'from-purple-500',
    'from-purple-600',
    'from-red-500',
    'from-red-600',
    'from-orange-500',
    'from-orange-600',
    'to-blue-600',
    'to-blue-700',
    'to-green-600',
    'to-green-700',
    'to-purple-600',
    'to-purple-700',
    'to-red-600',
    'to-red-700',
    'to-orange-600',
    'to-orange-700',
    'hover:from-blue-600',
    'hover:from-green-600',
    'hover:from-purple-600',
    'hover:from-red-600',
    'hover:from-orange-600',
    'hover:to-blue-700',
    'hover:to-green-700',
    'hover:to-purple-700',
    'hover:to-red-700',
    'hover:to-orange-700',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      colors: {
        // Design system colors from blog_design.pen
        brand: {
          dark: '#0A0A0F',
          darker: '#06060C',
          border: '#1A1A2E',
          text: {
            muted: '#A1A1AA',
            subtle: '#71717A',
            dimmer: '#3A3A5E',
          },
          primary: '#6366F1', // Indigo
        },
      },
    },
  },
  plugins: [],
}
