/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  safelist: [
    'bg-blue-50',
    'bg-blue-600',
    'bg-green-50',
    'bg-green-600',
    'bg-purple-50',
    'bg-purple-600',
    'bg-red-50',
    'bg-red-600',
    'bg-orange-50',
    'bg-orange-600',
    'text-blue-600',
    'text-green-600',
    'text-purple-600',
    'text-red-600',
    'text-orange-600',
    'from-blue-500',
    'from-blue-600',
    'from-green-500',
    'from-green-600',
    'from-purple-500',
    'from-purple-600',
    'from-red-500',
    'from-red-600',
    'from-orange-500',
    'from-orange-600',
    'to-blue-600',
    'to-blue-700',
    'to-green-600',
    'to-green-700',
    'to-purple-600',
    'to-purple-700',
    'to-red-600',
    'to-red-700',
    'to-orange-600',
    'to-orange-700',
    'hover:from-blue-600',
    'hover:from-green-600',
    'hover:from-purple-600',
    'hover:from-red-600',
    'hover:from-orange-600',
    'hover:to-blue-700',
    'hover:to-green-700',
    'hover:to-purple-700',
    'hover:to-red-700',
    'hover:to-orange-700',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
    },
  },
  plugins: [],
}
